apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blockchain
  name: blockchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blockchain
    spec:
      containers:
      - image: elmanhasa/blockchain-js:latest
        imagePullPolicy: Always
        name: blockchain
---
apiVersion: v1
kind: Service
metadata:
spec:
  type: ClusterIP
  ports:
    - targetPort: 30083
      port: 30083
    - targetPort: 8083
      port: 8083
  selector:
    app: blockchain
---
apiVersion: apps/v1
kind: Deployment2
metadata:
  creationTimestamp: null
  labels:
    app: blockchain2
  name: blockchain2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blockchain2
    spec:
      containers:
      - image: elmanhasa/blockchain-js:latest
        imagePullPolicy: Always
        name: blockchain2
---
apiVersion: v1
kind: Service
metadata:
spec:
  type: ClusterIP
  ports:
    - targetPort: 30083
      port: 30083
    - targetPort: 8083
      port: 8083
  selector:
    app: blockchain2